;;; lambert-putty.el --- 

;; Copyright 2012 
;;
;; Author: lambert_sun@NJ-LAMBERT-SUN <vangoals@gmail.com>
;; Version: $Id: lambert-putty.el,v 0.0 2012/11/21 10:23:05 lambert_sun Exp $
;; Keywords: 
;; X-URL: not distributed yet

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software
;; Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

;;; Commentary:

;; 

;; Put this file into your load-path and the following into your ~/.emacs:
;;   (require 'lambert-putty)

;;; Code:

(provide 'lambert-putty)

;; required features
(eval-when-compile
  (require 'color-theme))

;;;;##########################################################################
;;;;  User Options, Variables
;;;;##########################################################################


;; my own color theme
(defun my-color-theme ()
  "Color theme for putty."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "green")
      (foreground-color . "white")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (ac-fuzzy-cursor-color . "red")
      (anything-show-completion-face . highlight)
      (ascii-ascii-face . ascii-ascii-face)
      (ascii-non-ascii-face . ascii-non-ascii-face)
      (browse-kill-ring-separator-face . bold)
      (buffer-face-mode-face . variable-pitch)
      (compilation-message-face . underline)
      (curchg-default-cursor-color . "green")
      (curchg-input-method-cursor-color . "Orange")
      (diary-face . diary)
      (gnus-mouse-face . highlight)
      (gnus-summary-selected-face . gnus-summary-selected)
      (hl-line-face . hl-line)
      (hl-sexp-background-color . "#4b3b4b")
      (hs-face . hs-face)
      (hs-fringe-face . hs-fringe-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (moccur-maximum-displayed-with-color . 500)
      (multi-shell-use-ansi-color . t)
      (org-goto-interface . outline)
      (org-remember-interactive-interface . refile)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (term-default-bg-color . "Black")
      (term-default-fg-color . "Yellow")
      (top-mode-mark-face . highlight)
      (view-highlight-face . highlight)
      (w3m-form-mouse-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :foundry "unknown"))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-selection-face ((t (:background "Blue1" :foreground "grey90" :weight normal))))
     (ac-yasnippet-candidate-face ((t (:background "yellow" :foreground "black" :weight normal))))
     (ac-yasnippet-selection-face ((t (:background "DarkRed" :foreground "white" :weight normal))))
     (anything-M-x-key-face ((t (:foreground "orange" :underline t))))
     (anything-apt-installed ((t (:foreground "green"))))
     (anything-bmkext-file ((t (:foreground "Deepskyblue2"))))
     (anything-bmkext-gnus ((t (:foreground "magenta"))))
     (anything-bmkext-info ((t (:foreground "green"))))
     (anything-bmkext-man ((t (:foreground "Orange4"))))
     (anything-bmkext-no--file ((t (:foreground "grey"))))
     (anything-bmkext-w3m ((t (:foreground "yellow"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-buffer-not-saved ((t (:foreground "Indianred2"))))
     (anything-buffer-saved-out ((t (:foreground "red"))))
     (anything-emms-playlist ((t (:foreground "Springgreen4" :underline t))))
     (anything-ff-directory ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-ff-executable ((t (:foreground "green"))))
     (anything-ff-file ((t (:foreground "CadetBlue" :underline t))))
     (anything-ff-invalid-symlink ((t (:background "red" :foreground "black"))))
     (anything-ff-prefix ((t (:background "yellow" :foreground "black"))))
     (anything-ff-symlink ((t (:foreground "DarkOrange"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-grep-file ((t (:foreground "BlueViolet" :underline t))))
     (anything-grep-finish ((t (:foreground "Green"))))
     (anything-grep-lineno ((t (:foreground "Darkorange1"))))
     (anything-grep-match ((t (:background "Black" :foreground "Grey70" :weight normal))))
     (anything-grep-running ((t (:foreground "Red"))))
     (anything-header ((t (:background "Black" :foreground "Gold" :underline t))))
     (anything-isearch-match ((t (:background "White" :foreground "DarkRed"))))
     (anything-match ((t (:background "Black" :foreground "Grey70" :weight normal))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (ascii-ascii-face ((t (:background "grey90" :foreground "red3" :weight normal))))
     (ascii-non-ascii-face ((t (:background "Black" :foreground "SteelBlue2"))))
     (beautiful-blue-face ((t (:foreground "cornflower blue"))))
     (beautiful-blue-red-face ((t (:background "cornflower blue" :foreground "red"))))
     (black-red-face ((t (:background "red" :foreground "black"))))
     (blue-face ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "SpringGreen1" :height 1.1))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:weight normal))))
     (button ((t (:underline t))))
     (c-nonbreakable-space-face ((t (:background "red" :weight normal))))
     (cal-china-x-priority1-holiday-face ((t (:background "DarkRed" :foreground "White"))))
     (cal-china-x-priority2-holiday-face ((t (:background "Khaki" :foreground "Black"))))
     (calendar-today ((t (:background "black" :foreground "white" :underline t))))
     (change-log-acknowledgement ((t (:foreground "red" :height 1.05))))
     (change-log-conditionals ((t (:foreground "magenta3"))))
     (change-log-date ((t (:foreground "Deep Pink"))))
     (change-log-email ((t (:foreground "magenta3"))))
     (change-log-file ((t (:foreground "orchid2" :weight normal :height 1.2))))
     (change-log-function ((t (:foreground "magenta3"))))
     (change-log-list ((t (:foreground "DeepSkyBlue1" :weight normal :height 1.05))))
     (change-log-name ((t (:foreground "cyan"))))
     (chart-blue-dot ((t (:background "blue" :foreground "black"))))
     (chart-cyan-cross_weave ((t (:background "cyan" :foreground "black"))))
     (chart-green-scales ((t (:background "green" :foreground "black"))))
     (chart-purple-dimple3 ((t (:background "purple" :foreground "black"))))
     (chart-red-dimple1 ((t (:background "red" :foreground "black"))))
     (chart-yellow-boxes ((t (:background "yellow" :foreground "black"))))
     (comint-highlight-input ((t (:background "black" :foreground "gold3" :weight normal))))
     (comint-highlight-prompt ((t (:foreground "Green"))))
     (company-echo ((t (nil))))
     (company-echo-common ((t (:foreground "firebrick1"))))
     (company-preview ((t (:background "gold3" :foreground "black"))))
     (company-preview-common ((t (:background "gold3" :foreground "grey20"))))
     (company-preview-search ((t (:background "green4" :foreground "green"))))
     (company-tooltip ((t (:background "grey80" :foreground "black" :weight normal))))
     (company-tooltip-common ((t (:background "grey80" :foreground "blue1" :weight normal))))
     (company-tooltip-common-selection ((t (:background "DeepSkyBlue" :foreground "white" :weight normal))))
     (company-tooltip-mouse ((t (:background "DarkRed" :foreground "White"))))
     (company-tooltip-selection ((t (:background "DeepSkyBlue" :foreground "black" :weight normal))))
     (compilation-column-number ((t (:foreground "SpringGreen1"))))
     (compilation-error ((t (:foreground "red2" :weight normal))))
     (compilation-info ((t (:foreground "cyan"))))
     (compilation-line-number ((t (:foreground "RoyalBlue1"))))
     (compilation-warning ((t (:foreground "yellow" :weight normal))))
     (completions-annotations ((t (:underline nil :slant normal))))
     (completions-common-part ((t (:foreground "Green3"))))
     (completions-first-difference ((t (:foreground "Grey60"))))
     (cscope-file-face ((t (:foreground "DeepPink"))))
     (cscope-function-face ((t (:foreground "cyan"))))
     (cscope-line-face ((t (:foreground "RoyalBlue1"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cursor ((t (:background "green"))))
     (custom-button ((t (:background "darkred" :foreground "white" :box (:line-width 1 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "grey5" :foreground "green"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:foreground "gold" :underline t :weight normal))))
     (custom-group-tag ((t (:foreground "gold" :underline t :weight normal :height 1.2))))
     (custom-group-tag-1 ((t (:foreground "pink" :weight normal :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:foreground "cyan1" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:underline t :weight normal))))
     (custom-variable-tag ((t (:foreground "gold" :underline t :weight normal))))
     (custom-visibility ((t (:foreground "cyan1" :underline t :height 0.8))))
     (cyan-face ((t (:foreground "cyan"))))
     (darkblue-face ((t (:foreground "blue"))))
     (darkcyan-face ((t (:foreground "cyan"))))
     (darkgreen-face ((t (:foreground "green"))))
     (darkmagenta-face ((t (:foreground "magenta"))))
     (darkred-face ((t (:foreground "red"))))
     (darkyellow-face ((t (:foreground "yellow"))))
     (diary ((t (:foreground "yellow1"))))
     (diary-anniversary ((t (:weight normal :foreground "#00ffff" :height 1.0))))
     (diary-button ((t (nil))))
     (diary-time ((t (:weight normal :foreground "DeepPink" :height 1.0))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey70"))))
     (diff-file-header ((t (:background "grey60" :weight normal))))
     (diff-function ((t (:background "grey45"))))
     (diff-header ((t (:background "grey45"))))
     (diff-hunk-header ((t (:background "grey45"))))
     (diff-index ((t (:background "grey60" :weight normal))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:background "grey60" :weight normal))))
     (diff-refine-change ((t (:background "grey60"))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "orchid2" :weight normal :height 1.2))))
     (dired-flagged ((t (:foreground "red" :weight normal))))
     (dired-header ((t (:foreground "SpringGreen1" :height 1.1))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-lis-mode-line-face ((t (:background "darkmagenta" :foreground "white"))))
     (dired-mark ((t (:foreground "cyan"))))
     (dired-marked ((t (:foreground "red" :weight normal))))
     (dired-perm-write ((t (:foreground "red" :height 1.15))))
     (dired-symlink ((t (:foreground "DeepSkyBlue1" :weight normal :height 1.15))))
     (dired-warning ((t (:foreground "red" :weight normal))))
     (diredp-compressed-file-suffix ((t (:foreground "red" :height 1.15))))
     (diredp-date-time ((t (:foreground "yellow2" :height 1.12))))
     (diredp-deletion ((t (:background "Black" :foreground "red" :height 1.15))))
     (diredp-deletion-file-name ((t (:foreground "red" :weight normal :height 1.15))))
     (diredp-dir-heading ((t (:background "grey21" :foreground "red" :weight normal :height 1.3))))
     (diredp-dir-priv ((t (:background "Black" :foreground "DeepSkyblue2" :weight normal :height 1.2))))
     (diredp-display-msg ((t (:foreground "Gold" :height 1.2))))
     (diredp-exec-priv ((t (:background "Black" :foreground "red" :weight normal :height 1.15))))
     (diredp-executable-tag ((t (:foreground "Red" :weight normal :height 1.15))))
     (diredp-file-name ((t (:foreground "Green3" :weight normal :height 1.15))))
     (diredp-file-suffix ((t (:foreground "deep pink" :height 1.15))))
     (diredp-flag-mark ((t (:background "Black" :foreground "yellow" :weight normal :height 1.15))))
     (diredp-flag-mark-line ((t (:background "Black" :foreground "yellow" :weight normal :height 1.15))))
     (diredp-ignored-file-name ((t (:foreground "Green4" :weight normal :height 1.15))))
     (diredp-link-priv ((t (:foreground "blue1" :weight normal :height 1.15))))
     (diredp-no-priv ((t (:background "Black" :foreground "brown1" :weight normal :height 1.15))))
     (diredp-other-priv ((t (:background "Black" :foreground "khaki" :weight normal :height 1.15))))
     (diredp-rare-priv ((t (:background "Black" :foreground "Red" :weight normal :height 1.15))))
     (diredp-read-priv ((t (:background "Black" :foreground "yellow" :weight normal :height 1.15))))
     (diredp-symlink ((t (:foreground "orchid1" :weight normal :height 1.15))))
     (diredp-write-priv ((t (:background "Black" :foreground "SkyBlue1" :weight normal :height 1.15))))
     (diredp-number ((t (:background "Black" :foreground "Red3" :weight bold :height 1.1))))
     (dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1.1 :width normal :foundry "unknown"))))
     (dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1.1 :width normal :foundry "unknown"))))
     (eclim-problems-highlight-error-face ((t (:underline "red"))))
     (eclim-problems-highlight-warning-face ((t (:underline "orange"))))
     (ediff-current-diff-A ((t (:background "blue1" :foreground "white"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "SpringGreen1" :foreground "black"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "Black"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "Black"))))
     (ediff-even-diff-C ((t (:background "Grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "blue1" :foreground "white"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "white"))))
     (ediff-fine-diff-B ((t (:background "SpringGreen1" :foreground "black"))))
     (ediff-fine-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "black"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "Grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "black"))))
     (ediff-trees-deleted-original-face ((t (:background "Pink"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:foreground "Red" :weight normal))))
     (ffap ((t (:background "DarkRed" :foreground "White" :height 1.1))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (fixme-face ((t (:foreground "red2" :box (:line-width 1 :color "red2") :weight bold))))
     (flymake-errline ((t (:background "red2" :foreground "White"))))
     (flymake-warnline ((t (:background "Gold3" :foreground "Black"))))
     (fringe ((t (:background "grey7"))))
     (green-face ((t (:foreground "green"))))
     (green-red-face ((t (:background "red" :foreground "green"))))
     (header-line ((t (:background "Black" :foreground "red"))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (:weight normal))))
     (hi-black-hb ((t (:weight normal :height 1.67))))
     (hi-blue ((t (:background "light blue" :foreground "black"))))
     (hi-blue-b ((t (:foreground "blue1" :weight normal))))
     (hi-green ((t (:background "green1" :foreground "black"))))
     (hi-green-b ((t (:foreground "green1" :weight normal))))
     (hi-pink ((t (:background "pink" :foreground "black"))))
     (hi-red-b ((t (:foreground "red1" :weight normal))))
     (hi-yellow ((t (:background "yellow1" :foreground "black"))))
     (hide-ifdef-shadow ((t (:foreground "grey70"))))
     (highlight ((t (:background "DarkRed" :foreground "White"))))
     (highlight-cl ((t (:foreground "#20ABFC" :underline nil))))
     (highlight-cl-and-other ((t (:foreground "#20ABFC" :underline nil))))
     (highlight-cl-macro ((t (:underline nil))))
     (highlight-symbol-face ((t (:background "black" :foreground "white" :weight normal :height 1.1))))
     (hl-line ((t (:background "grey8"))))
     (hl-paren-face ((t (nil))))
     (hl-sexp-face ((t (:background "gray2"))))
     (hlt-property-highlight ((t (:background "Navy"))))
     (holiday ((t (:background "chocolate4"))))
     (hs-face ((t (:background "DarkRed" :foreground "grey" :box (:line-width 1 :color "grey50")))))
     (hs-fringe-face ((t (:background "DarkRed" :foreground "grey" :box (:line-width 2 :color "grey75" :style released-button)))))
     (ido-first-match ((t (:foreground "DeepPink" :weight normal))))
     (ido-incomplete-regexp ((t (:foreground "red" :weight normal))))
     (ido-indicator ((t (:background "red1" :foreground "SteelBlue1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "SteelBlue1" :weight normal))))
     (ifdef-highlight-face1 ((t (:background "paleturquoise4"))))
     (ifdef-highlight-face2 ((t (:background "paleGreen3"))))
     (ifdef-highlight-face3 ((t (:background "yellow4"))))
     (ifdef-highlight-face4 ((t (:background "pink4"))))
     (info-command-ref-item ((t (:background "DimGray" :foreground "#7474FFFF7474"))))
     (info-file ((t (:background "Black" :foreground "Blue"))))
     (info-function-ref-item ((t (:background "DimGray" :foreground "#4D4DDDDDDDDD"))))
     (info-header-node ((t (:italic t :foreground "white" :slant italic :weight normal))))
     (info-header-xref ((t (:foreground "cyan1" :underline t))))
     (info-macro-ref-item ((t (:background "DimGray" :foreground "Yellow"))))
     (info-menu ((t (:foreground "DarkRed"))))
     (info-menu-header ((t (:foreground "khaki3" :weight normal :family "Sans Serif"))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :foreground "white" :slant italic :weight normal))))
     (info-quoted-name ((t (:foreground "Purple"))))
     (info-reference-item ((t (:background "DimGray"))))
     (info-single-quote ((t (:foreground "Green" :weight normal :height 1.05))))
     (info-special-form-ref-item ((t (:background "DimGray" :foreground "Yellow"))))
     (info-string ((t (:foreground "Grey50"))))
     (info-syntax-class-item ((t (:background "DimGray" :foreground "#FFFF9B9BFFFF"))))
     (info-title-1 ((t (:foreground "Gold" :weight normal :height 1.3310000000000004))))
     (info-title-2 ((t (:foreground "red" :weight normal :height 1.2100000000000002))))
     (info-title-3 ((t (:foreground "DodgerBlue" :weight normal :height 1.1))))
     (info-title-4 ((t (:foreground "Green" :weight normal))))
     (info-user-option-ref-item ((t (:background "DimGray" :foreground "Red"))))
     (info-variable-ref-item ((t (:background "DimGray" :foreground "Orange"))))
     (info-xref ((t (:foreground "cyan1" :underline t))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "Springgreen1" :foreground "black"))))
     (isearch-fail ((t (:background "grey90" :foreground "red2"))))
     (iswitchb-current-match ((t (:foreground "SteelBlue1" :weight normal :height 1.1))))
     (iswitchb-invalid-regexp ((t (:foreground "red2" :weight normal))))
     (iswitchb-single-match ((t (:foreground "SpringGreen1" :height 1.1))))
     (iswitchb-virtual-matches ((t (:foreground "DeepPink1"))))
     (italic ((t (:underline nil :slant normal))))
     (lazy-highlight ((t (:background "grey20"))))
     (light-blue-face ((t (:foreground "cornflower blue"))))
     (lightblue-face ((t (:foreground "cornflower blue"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (linum ((t (:background "black" :foreground "grey70"))))
     (log-edit-header ((t (:foreground "DeepSkyBlue1" :weight normal :height 1.1))))
     (log-edit-summary ((t (:foreground "orchid2" :weight normal :height 1.1))))
     (log-edit-unknown-header ((t (:foreground "red" :height 1.1))))
     (magenta-face ((t (:foreground "magenta"))))
     (match ((t (:bold t :background "Black" :foreground "Grey70" :weight extra-bold))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:foreground "chartreuse1" :weight normal))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :foreground "yellow" :slant italic :weight normal))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:foreground "DarkOliveGreen1" :weight normal))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (mew-face-body-cite1 ((t (:foreground "LimeGreen" :weight normal))))
     (mew-face-body-cite2 ((t (:foreground "SkyBlue" :weight normal))))
     (mew-face-body-cite3 ((t (:foreground "violet" :weight normal))))
     (mew-face-body-cite4 ((t (:foreground "Gold" :weight normal))))
     (mew-face-body-cite5 ((t (:foreground "OrangeRed" :weight normal))))
     (mew-face-body-comment ((t (:foreground "gray50" :weight normal))))
     (mew-face-body-url ((t (:foreground "OrangeRed" :weight normal))))
     (mew-face-eof-message ((t (:foreground "LimeGreen" :weight normal))))
     (mew-face-eof-part ((t (:foreground "Gold" :weight normal))))
     (mew-face-header-date ((t (:foreground "LimeGreen" :weight normal))))
     (mew-face-header-from ((t (:foreground "Gold" :weight normal))))
     (mew-face-header-important ((t (:foreground "SkyBlue" :weight normal))))
     (mew-face-header-key ((t (:foreground "LimeGreen" :weight normal))))
     (mew-face-header-marginal ((t (:foreground "gray50" :weight normal))))
     (mew-face-header-private ((t (:weight normal))))
     (mew-face-header-subject ((t (:foreground "OrangeRed" :weight normal))))
     (mew-face-header-to ((t (:foreground "violet" :weight normal))))
     (mew-face-header-warning ((t (:foreground "red" :weight normal))))
     (mew-face-header-xmew ((t (:foreground "chocolate" :weight normal))))
     (mew-face-header-xmew-bad ((t (:foreground "red" :weight normal))))
     (mew-face-mark-delete ((t (:foreground "OrangeRed" :weight normal))))
     (mew-face-mark-escape ((t (:foreground "violet" :weight normal))))
     (mew-face-mark-refile ((t (:foreground "LimeGreen" :weight normal))))
     (mew-face-mark-review ((t (:foreground "SkyBlue" :weight normal))))
     (mew-face-mark-unlink ((t (:foreground "Gold" :weight normal))))
     (mew-face-mark-unread ((t (:weight normal))))
     (minibuffer-prompt ((t (:foreground "SteelBlue1"))))
     (mode-line ((t (:background "DarkRed" :foreground "white" :box (:line-width -1 :style released-button) :height 0.91))))
     (mode-line-buffer-id ((t (:weight normal))))
     (mode-line-emphasis ((t (:weight normal))))
     (mode-line-highlight ((t (:box (:line-width 1 :color "Green4" :style released-button)))))
     (mode-line-inactive ((t (:background "grey10" :foreground "white" :box (:line-width -1 :style released-button) :weight light :height 0.91))))
     (modelinepos-column-warning ((t (:foreground "Red"))))
     (mouse ((t (:background "black"))))
     (next-error ((t (:background "SteelBlue3" :foreground "white"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "green" :weight bold))))
     (nxml-attribute-prefix ((t (:foreground "yellow"))))
     (nxml-attribute-value ((t (:foreground "DeepPink"))))
     (nxml-attribute-value-delimiter ((t (:foreground "Deep pink"))))
     (nxml-cdata-section-CDATA ((t (:foreground "yellow"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "cyan"))))
     (nxml-char-ref-number ((t (:foreground "cyan"))))
     (nxml-comment-content ((t (:foreground "yellow" :height 1.05))))
     (nxml-comment-delimiter ((t (:foreground "yellow" :height 1.05))))
     (nxml-delimited-data ((t (:foreground "khaki4"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "red2" :weight normal :height 1.2))))
     (nxml-element-prefix ((t (:foreground "yellow"))))
     (nxml-entity-ref-delimiter ((t (:foreground "cyan"))))
     (nxml-entity-ref-name ((t (:foreground "cyan"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal :foundry "misc"))))
     (nxml-hash ((t (:foreground "yellow"))))
     (nxml-heading ((t (:weight normal))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "yellow"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "magenta3"))))
     (nxml-namespace-attribute-value ((t (:foreground "Deep pink"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "Deep pink"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "yellow"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box 1 :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown"))))
     (nxml-outline-ellipsis ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown"))))
     (nxml-outline-indicator ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown"))))
     (nxml-processing-instruction-content ((t (:foreground "khaki4"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "DeepSkyBlue1" :weight normal :height 1.05))))
     (nxml-prolog-keyword ((t (:foreground "DeepSkyBlue1" :weight normal :height 1.05))))
     (nxml-prolog-literal-content ((t (:foreground "khaki4"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "khaki4"))))
     (nxml-ref ((t (:foreground "cyan"))))
     (nxml-tag-delimiter ((t (:foreground "red2" :weight normal :height 1.2))))
     (nxml-tag-slash ((t (:foreground "red2" :weight normal :height 1.2))))
     (nxml-text ((t (nil))))
     (one-key-keystroke ((t (:foreground "DarkRed"))))
     (one-key-prompt ((t (:foreground "khaki3"))))
     (one-key-title ((t (:foreground "Gold"))))
     (org-agenda-calendar-event ((t (:foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :height 113))))
     (paren-face-match ((t (:background "magenta" :foreground "yellow"))))
     (paren-face-mismatch ((t (:background "red" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (query-replace ((t (:background "DeepPink" :foreground "black"))))
     (red-blue-face ((t (:background "blue" :foreground "red"))))
     (red-face ((t (:foreground "red"))))
     (red-yellow-face ((t (:background "yellow" :foreground "red"))))
     (region ((t (:background "grey25" :foreground "white"))))
     (region-invert ((t (nil))))
     (saint/iswitchb-highlight-1-face ((t (:foreground "IndianRed1"))))
     (saint/iswitchb-highlight-2-face ((t (:foreground "DarkSeaGreen3"))))
     (saint/iswitchb-highlight-3-face ((t (:foreground "#7f7f7f"))))
     (scroll-bar ((t (nil))))
     (search-buffers-face ((t (:background "SkyBlue" :foreground "Black" :weight normal))))
     (search-buffers-header-face ((t (:background "gray20" :foreground "azure3" :weight normal))))
     (secondary-selection ((t (:background "Black"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (sgml-namespace ((t (:foreground "yellow"))))
     (sh-escaped-newline ((t (:foreground "Deep Pink"))))
     (sh-heredoc ((t (:foreground "yellow1" :weight normal))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "green" :foreground "black" :weight normal))))
     (show-paren-mismatch ((t (:background "red" :foreground "black" :weight normal :height 1.5))))
     (show-ws-hard-space ((t (:background "PaleGreen"))))
     (show-ws-tab ((t (:background "LemonChiffon"))))
     (show-ws-trailing-whitespace ((t (:background "Gold"))))
     (showtip-face ((t (:background "black" :foreground "White" :height 1.15))))
     (srecode-separator-face ((t (:strike-through t :weight normal))))
     (tabbar-button ((t (:background "black" :foreground "green" :box (:line-width 1 :color "green" :style released-button) :height 0.97))))
     (tabbar-button-highlight ((t (:background "black" :foreground "green" :box (:color "green") :height 0.97))))
     (tabbar-default ((t (:height 0.97))))
     (tabbar-highlight ((t (:underline t))))
     (tabbar-selected ((t (:background "black" :foreground "DeepSkyBlue" :box (:line-width 1 :color "RoyalBlue4" :style released-button) :weight normal :height 0.97 :weight normal))))
     (tabbar-separator ((t (:background "black" :foreground "gray50" :height 0.97))))
     (tabbar-unselected ((t (:background "black" :foreground "steelblue4" :box (:line-width 1 :color "gray2" :style pressed-button) :height 0.97 :weight normal))))
     (tcl-escaped-newline ((t (:foreground "Deep Pink"))))
     (template-message-face ((t (:weight normal))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "grey10" :foreground "DeepSkyBlue1" :height 1.15))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (underline-face ((t (:underline t))))
     (underline-green-face ((t (:foreground "green" :underline t))))
     (undo-tree-visualizer-active-branch-face ((t (:foreground "white" :weight normal))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (white-face ((t (:foreground "white"))))
     (white-red-face ((t (:background "red" :foreground "white"))))
     (widget-button ((t (:weight normal))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "grey10" :foreground "DeepSkyBlue"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "grey10" :foreground "DeepSkyBlue"))))
     (window-number-face ((t (:foreground "yellow" :weight normal :height 1.1))))
     (wuxch-dired-avi-face ((t (:foreground "magenta3" :height 1.2))))
     (wuxch-dired-doc-face ((t (:foreground "red" :weight normal :height 1.2))))
     (wuxch-dired-elisp-face ((t (:foreground "DeepSkyBlue1" :weight normal :height 1.2))))
     (wuxch-dired-exe-face ((t (:foreground "orchid2" :weight normal :height 1.2))))
     (xref-keyword-face ((t (:foreground "grey"))))
     (xref-list-pilot-face ((t (:foreground "gold"))))
     (xref-list-symbol-face ((t (:foreground "green"))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "grey20" :foreground "gold"))))
     (yellow-blue-face ((t (:background "blue" :foreground "yellow"))))
     (yellow-face ((t (:foreground "yellow"))))
     (yellow-forestgreen-face ((t (:background "forest green" :foreground "yellow"))))
     (yellow-red-face ((t (:background "red" :foreground "yellow"))))
     (zjl-hl-parameters-reference-face ((t (:foreground "DeepPink1" :weight normal)))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))

(eval-after-load "lambert-putty"
  '(my-color-theme))

;;; lambert-putty.el ends here
